apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: deltaprojects/kafka-manager:v3.0.0.6-2
        ports:
        - containerPort: 9000
        env:
        - name: ZK_HOSTS
          value: zookeeper-1:2181,zookeeper-2:2181
        - name: KAFKA_MANAGER_USERNAME
          value: "admin"
        - name: KAFKA_MANAGER_PASSWORD
          value: "password"