apiVersion: v1
kind: Service
metadata:
  name: extended-api-for-ditto-svc
  labels:
    app.kubernetes.io/name: extended-api-for-ditto
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: extended-api-for-ditto
