apiVersion: v1
kind: Service
metadata:
  name: pivot-rest-deploy
spec:
  selector:
    name: pod-pivot-rest-deploy
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 7998
    nodePort: 30667
    targetPort: 8001
