apiVersion: v1
kind: PersistentVolume
metadata:
  name: dt-pv-grafana
spec:
  accessModes:
   - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/dt-platform/grafana
    type: DirectoryOrCreate
