apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-device-registry
spec:
  accessModes: 
   - ReadWriteOnce
  capacity:
    storage: 1Mi
  hostPath:
    path: /mnt/dt-platform/cloud2edge
    type: DirectoryOrCreate