hono:
  prometheus:
    createInstance: false
  grafana:
    enabled: false
  useLoadBalancer: false
ditto:
  mongodb:
    persistence:
      enabled: true
      existingClaim: dt-pvc-mongodb
    volumePermissions:
      enabled: true
  nginx:
    service:
      nodePort: 30525
